version: "3.7"
services:
  hiveapp:
    image: jordangrindrod/hiveapp
    build: .
    ports:
      - target: 8000
        published: 8000
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - hivedb
  hivedb:
    image: jordangrindrod/hivedb
    build: ./database/.
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
